version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t ocr-lettings-app:latest --build-arg SECRET_KEY=${SECRET_KEY} .
      - run:
          name: Run tests inside Docker image
          command: docker run -e SECRET_KEY=${SECRET_KEY} ocr-lettings-app:latest pytest

  deploy:
    machine: true
    steps:
      - run:
          name: Dockerhub > login, tag & push
          command: |
            docker build -t ocr-lettings-app:latest --build-arg SECRET_KEY=${SECRET_KEY} .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag ocr-lettings-app $DOCKERHUB_USERNAME/ocr-lettings-app:latest
            docker push $DOCKERHUB_USERNAME/ocr-lettings-app:latest
      - run:
          name: Install Heroku CLI
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Login to Heroku container registry
          command: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - run:
          name: tag Docker image for heroku
          command: docker tag ocr-lettings-app:latest registry.heroku.com/lettings-app/web
      - run:
          name: Push and release Docker image to Heroku registry
          command: |
            docker push registry.heroku.com/lettings-app/web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web --app lettings-app
  
workflows:
  heroku deployment process:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
